# api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gendi97/todo-backend:01
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/todos"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
