apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: my-app
type: Opaque
data:
  mongodb-root-username: dXNlcm5hbWU=  # base64 encoded value of 'username'
  mongodb-root-password: cGFzc3dvcmQ=  # base64 encoded value of 'password'
