name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
env:
  KUBECONFIG: | 
    YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
    cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VSQ1ZF
    TkRRV1V5WjBGM1NVSkJaMGxKWXpSTlVrMDJZWFVyUTJkM1JGRlpTa3R2V2tsb2RtTk9RVkZGVEVK
    UlFYZEdWRVZVVFVKRlIwRXhWVVVLUVhoTlMyRXpWbWxhV0VwMVdsaFNiR042UVdWR2R6QjVUa1JC
    TWsxRVJYaFBWRVY2VFdwR1lVWjNNSHBPUkVFeFRYcEJlRTlVUlRSTmFrWmhUVUpWZUFwRmVrRlNR
    bWRPVmtKQlRWUkRiWFF4V1cxV2VXSnRWakJhV0UxM1oyZEZhVTFCTUVkRFUzRkhVMGxpTTBSUlJV
    SkJVVlZCUVRSSlFrUjNRWGRuWjBWTENrRnZTVUpCVVVObk9VZFpXaTlpTDNSeGRuTldiRGQ2WjFN
    elJubEhTVmhvVFc5WWREQmxTR2R6VFVwUGEzVnZlRkk0YzBOUFF6QnlSbWhZVW5KSFYwOEtXbVZS
    UjJwWFdsZGhTbnBaVERNNFVFaDZUbWQ1WWxjeVMzSlVSMlZGYUhkc1ZtbHlVa3BsZUVSS2MyMHda
    a3hwU1U5V2RFOHpWSG94ZURoTFFsZGlkZ3BqTmxwa01FaHBhMUYyWldKa1JWTjRjbTh2YVRSUGQw
    dENVVnA2YTJka2RtbzBNbkJ6TUROV2NrTkVhMVIwZDFWME1IaDBUMEYyYlZOSlJXOWpiVmhHQ2tG
    aVFWRjVSVzFRYmxFMWJVRlFUbVl3TTJwS01VTk9Wa2xHU2pkNE5VMUhXWFIyVEZWVU9YUTRTVzB3
    UWxCNVZsY3dVbU5hU1d4QlEwcHNTVmhzWVdJS1FWTjBaVzVTWkZCc1JIazFWbkZKT0VSa01rTXlX
    RWwxWkdsUFNVOWxVRTlvWmpCRU5tZEpOVTlTWnpsM1JVb3Jiemd6T1ZneFlVbFZTbVpNYVZOYWRn
    cENMMEZJU1hwSlNtcERSVmxMTUM5a01rdzVia3RDZG5rNVZDdFFRV2ROUWtGQlIycFhWRUpZVFVF
    MFIwRXhWV1JFZDBWQ0wzZFJSVUYzU1VOd1JFRlFDa0puVGxaSVVrMUNRV1k0UlVKVVFVUkJVVWd2
    VFVJd1IwRXhWV1JFWjFGWFFrSlNablp3ZEdGbFRYTndRVGx6Vm10WGVqaFJlRVYxYUdwYVQzRlVR
    VllLUW1kT1ZraFNSVVZFYWtGTloyZHdjbVJYU214amJUVnNaRWRXZWsxQk1FZERVM0ZIVTBsaU0w
    UlJSVUpEZDFWQlFUUkpRa0ZSUVVGWk9USTFaekJTVlFvclZYZGFSVk5VTkRCVlFtWjNPRnBTZHl0
    dlpWSk5Xalk0VVVOWFkyOTROblpPT1daWFkyaDNaa2RyVFdoRk1ITkVZMFZqWlhOU2RUVllZVEZY
    U2pOc0NtODRlalpoUjI1Tk1tdDFOMUppWW5oQ2IxVmxiWEI1Wm1weVJITkZRbTR5VURSa1VtSk5l
    a0ZsYmxSVVpYRkVXaTgxZVU5aVExb3dVbUV3ZWpaWlJVa0tjMU54WjJsWFRHcFRXRWRwVkVsbGJu
    SXhLMEZhVHpsMWQzSlNSM0IzUkc5UGJVSnpOamhsVDFkSWR6UnhOa3h4V0VsMWRFc3liMjEzU2pK
    MU1UTlRlUXBSZW5wek9FVkZVbXg0YkVWWmJraENTVGg1TWpoS1NsTllOVUlyV1RsUFRuTXZiVWt3
    UXpZd1MzWktlRnBPU1RKSFJIWlRjVVJEYUZSc01uaHJlVTA1Q2l0TWJGTm1XQzg0VmxWeWVqVktT
    Mk4xWWxoWFdFeG9ZMk41YzJoeU5GSnRPWHBGUjBkRVdXRm5hM1pQVmpWcVJEVXZRVWhTU0ZKT1Js
    aDJVSGxNWlZRS01HRlJPVVpVVFhoVVRrMVVDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMw
    dExTMEsKICAgIHNlcnZlcjogaHR0cHM6Ly84OS4xMTcuNTguMTY3OjY0NDMKICBuYW1lOiBjbHVz
    dGVyLmxvY2FsCmNvbnRleHRzOgotIGNvbnRleHQ6CiAgICBjbHVzdGVyOiBjbHVzdGVyLmxvY2Fs
    CiAgICBuYW1lc3BhY2U6IHVuaWxldmVyLWRldgogICAgdXNlcjoga3ViZXJuZXRlcy1hZG1pbgog
    IG5hbWU6IGt1YmVybmV0ZXMtYWRtaW5AY2x1c3Rlci5sb2NhbApjdXJyZW50LWNvbnRleHQ6IGt1
    YmVybmV0ZXMtYWRtaW5AY2x1c3Rlci5sb2NhbApraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9
    CnVzZXJzOgotIG5hbWU6IGt1YmVybmV0ZXMtYWRtaW4KICB1c2VyOgogICAgY2xpZW50LWNlcnRp
    ZmljYXRlLWRhdGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVVJM
    VkVORFFXaEhaMEYzU1VKQlowbEpXWGN6VmtsNlJXaFVMMUYzUkZGWlNrdHZXa2xvZG1OT1FWRkZU
    RUpSUVhkR1ZFVlVUVUpGUjBFeFZVVUtRWGhOUzJFelZtbGFXRXAxV2xoU2JHTjZRV1ZHZHpCNVRr
    UkJNazFFUlhoUFZFVjZUV3BHWVVaM01IbE9WRUUwVFZSQmVVMXFRVEZPVkdSaFRVUjNlQXBJZWtG
    a1FtZE9Wa0pCYjFSR2JYUXhXVzFXYUZwSE1EWlpNbmd4WXpOU2JHTnBNV2hhUnpGd1ltNU5lRWRV
    UVZoQ1owNVdRa0ZOVkVWSGRERlpiVlo1Q21KdFZqQmFXRTEwV1ZkU2RHRlhOSGRuWjBWcFRVRXdS
    ME5UY1VkVFNXSXpSRkZGUWtGUlZVRkJORWxDUkhkQmQyZG5SVXRCYjBsQ1FWRkVSSE5DWWs0S1ky
    aEZWM3BhZWxGalJXWndWamhRWW1aYVptVnlkMFJYVkhSS1RuQkZUbGNyTVZKdVdqRXpSekZOSzJk
    eFRuWkhSVzl2V0RkeVZqSm1OVzF6TWpKdFdRb3ZOVkZ0VEZkTldFSlVlSHBLY2pFNFYxcDBNRkYw
    S3psMVNrc3hlV3QyZHpGaFZsSnFSbEl4Y2pad2RGa3lSRmxQU1ZwaGVISnZjbEp5UjFGdVZqRlND
    bVZ5UWs5blprRnpRWG8wZW1sWmNIVmhNbkJ2VERGd1ZqSlFlRkZWZFN0YWFXSTVRa0U0ZGxWQmJ6
    WnNWVmh4VTFkeVlubFVXR3N2TkV0bWFtZFJTbVFLYWtoMWVGcExOVFp5VVVacE1VaFVjWEpOVGtJ
    eU9TOXhiRGR2YVdKSVVtRmliekV4TW1oQlptWlJaa1ZDWmxCeVZEVTBRMlpJSzNwcFZHczNTR2gz
    YXdwME5uTnVNV05RUkVsRFVVeFlOMUZJWVd0T04ycEhTbTVPT1V0RGFtNVViVzFMWVRGUk5WZGlh
    MDlNVFZaRlRUVTFNRzgyYWtocFVqZHZXbU42WkZVMkNsWktWWGhIZDNsMmNVaHVObGwwTnpOQlow
    MUNRVUZIYWxacVFsVk5RVFJIUVRGVlpFUjNSVUl2ZDFGRlFYZEpSbTlFUVZSQ1owNVdTRk5WUlVS
    RVFVc0tRbWRuY2tKblJVWkNVV05FUVdwQlRVSm5UbFpJVWsxQ1FXWTRSVUZxUVVGTlFqaEhRVEZW
    WkVsM1VWbE5RbUZCUmtZcksyMHhjRFI1ZVd0RU1uaFhVZ3BpVUhoRVJWTTJSMDVyTm5CTlFUQkhR
    MU54UjFOSllqTkVVVVZDUTNkVlFVRTBTVUpCVVVOU2N6bFhiRmhzU1RObVJ6VkllRTF2UlRSdmRX
    TXdXRGxhQ2xkT09ETlpkREpRVW5kd1JXaHJObU5pWTFkTmFqZzJSR2xOY0hKdVVXaENibXAzUVdz
    MldpdGlMelZIVGtGUGNXdHZhVzlzYzFSblRtdHhTVXhrTlRnS1NVNXpjRXB5T1RGWVVsSnJOMlZz
    YzJsNE9HeFNUMmRTV0VRMkszWndZV05OUVRObGFYbzFUbEJoYlRWM09XMXNZVVpxU2xJMVkxWXpj
    SGwxVjJweVVncHNVMDk2YmtkeU5tOWlkMUpIU0VOdlpuQmlhM2hsTTBoYU1qUlpRbUZqZWxaYWIx
    UlNkMWMwZW0xU01VZE1SR0Y1ZFdNeUt6UkVkWGhXZDNjelRVWldDako0TW1SdFQyUlFWR00yUVRC
    aVdtVkphRmRaUjA4d2RtbHJUbFp6VFZONFYyVXlZVzUxYjFjeVQyTldka00zVTFac1dXTXJaa2h2
    Ykd4T01sZHRaelFLZWtKbk5HcHFWa1ZRTjNWMWVVZEtNbTUwUlVOTVZIYzJSRVZDVG1aQmQxZFZX
    RmhpYTJaTFZYSTVaMU40WkhBMFJIUTRNQzl1Ym1oblEyODNDaTB0TFMwdFJVNUVJRU5GVWxSSlJr
    bERRVlJGTFMwdExTMEsKICAgIGNsaWVudC1rZXktZGF0YTogTFMwdExTMUNSVWRKVGlCU1UwRWdV
    RkpKVmtGVVJTQkxSVmt0TFMwdExRcE5TVWxGYjNkSlFrRkJTME5CVVVWQmR6ZEJWM3BZU1ZKR2N6
    SmpNRWhDU0RaV1prUXlNekpZTTNFNFFURnJOMU5VWVZKRVZuWjBWVm95WkdSNGRGUlFDbTlMYW1K
    NGFFdExSaXMyTVdSdUsxcHlUblJ3YlZBclZVcHBNV3BHZDFVNFkzbGhPV1pHYldKa1JVeG1kbUpw
    VTNSamNFdzRUbGRzVlZsNFZXUmhLM0VLWWxkT1p6SkVhVWRYYzJFMlN6QmhlR3RLTVdSVldIRjNW
    RzlJZDB4QlRTdE5ORzFMWW0xMGNXRkRPV0ZXWkdvNFZVWk1kbTFaYlM5UlVWQk1NVUZMVHdwd1Zr
    WTJhMnh4TWpock1UVlFLME51TkRSRlExaFplRGR6VjFOMVpYRXdRbGwwVWpBMmNYcEVVV1IyWmpa
    d1pUWkpiWGd3VjIwMlRtUmtiMUZJTXpCSUNuaEJXSG8yTUN0bFFXNTRMM00wYXpWUGVEUmpTa3hs
    Y2tvNVdFUjNlVUZyUXpFck1FSXljRVJsTkhocFducG1VMmR2TlRBMWNHbHRkRlZQVm0wMVJHa0tl
    a1pTUkU5bFpFdFBiM2cwYTJVMlIxaE5NMVpQYkZOV1RWSnpUWEkyYURVcmJVeGxPWGRKUkVGUlFV
    SkJiMGxDUVVWaVUzRlVORXg0V1VkVFVYVnVlQXBoVTFaaWJsVm5TVU5ZYjFCeWJXSm9kV2d4Wkd0
    UU1tWkZjVzlzTnk5MWVFMDNMeloyVTJaUWRDdHFNMlpRWkRWTlVEUjBiblZqTDNkTVpXTm1OWFJ4
    Q2xOeWJVZFZUbVkzWld4aE1tbFdSMXA0YjJSRGQzWTVWRFF6VWtSTVMwa3pVa3RCTkdOdGJIVTRO
    MnhSTmxSdlYyRk9aR3hFVFhkaVkydHVTRzR3ZG1VS2JFcHRSV04yVTBweVkxbDBUbE15VTNwaFlX
    OXFXWHAwU0V0dlJHVndjVmR5UmpGa01uUnJiMnhIYXpnM1RUUnRRMkZyT1ROV1lYaExSVk5ETm1K
    MVpnb3ZWM0pzYmxNd05UWkVjRVpSV0VjelR6ZG1MMVpJWkRkb2JrZ3hkWEoxTkhBMlNWRkViblZh
    UW1kdFlscGhaVzE0ZDNkalRFVmlNRkp5TVZwcFdHZFlDbmszY1ZCSlUzUndaa0p2VFRRelREbEVh
    VVJrZFZkMFduUm5LMUpoYlhweFFUSllMM0ZTZHpWelZGaDVRbkpFVWtkRFFXeDBVWHBRYkcxT1ZX
    NVpRVWNLT0hoblozWmlSVU5uV1VWQk1rUkxORmhhWjBvcldqUnVOME5TUjBGYVJVbFhXSEpOY0hG
    ellTOW1OMEYyVjJoak1rbFVORUZUYVdoaFNtZG5VbTEwVGdwTmNWTjJjSGxxWld4MFVWUXhhRWhE
    YkVZMlVuaGhkRUpDTDFkU00wWlVZbTV4V2xaaGMxcDFUbXRTYVcxUVVqSkhTRGh6YVZJNGExZE5U
    VUkzYnpCWkNuVlZUVVJaVGsxQ1JsRk5VVEV2ZGtaUU4ycHBRVzVtTUZCSmVUbHZUbWw0Vlc5TlFt
    cDVMMmx1Tm1Fd1FtRTFRMFJWVXpCell6aERaMWxGUVRVM1lUY0thVzFMY0VnNWJFMUxPV3BTYW10
    emNHYzVMM0pOVUhWc2NXcDJSR3R6ZVdrME1GazVaMHB3TlRWMk16bEpNVTFaTTJGYVJIazNjRkJo
    Vkc5dFFrc3haQXBMWVd4T1dFODRVR2RsYjJ4M2JsRkpZVE5CT0dkcWRsaEpPWFpCV0hselZrSjRR
    MUpOZHl0bFJWb3JPVVZSVjBSNU9TdDRTV0VyVFhwa1ZERkhaekZqQ210elVpdHVkQzlHTUV0ME5W
    bEhXRUl6UlVJNFJrVmxRbGRSTW14VWFGUmhOWFJ4U0d0c2EwTm5XVUlyTkV3d09FTkRZMHRtUW5W
    WWVFOHphM0V6V0VnS09WZzBNamRqUjI5blEwbHBlR2xXS3pKQlNXNTNLekU1TUZwR1dGbHJPWEYz
    YVZadWNERXJRME55U1dSa2EzcElMeTkyZVd0dU9WZHhXRXBTWVU5a0t3cFpjMVpOU2xkdE1uQlZi
    SEl4UlU5bFQzSjNjazlOUWlzMmRYRjFWV1JZU20wMU9WYzJiRE12VFRnMWJIZHdZazkyTjFNM2JV
    TlJXV2xOZDJOdmFUZHRDbUZ2VnpKMk0xcDZSbFZWWlRsR1drWk1VMWxUUm5kTFFtZEdhRXhvUjJz
    eVRWUlpSM0Z2VkcxNVQzVk5OM0JRYlRWdmMzbDVVM295VDNjNFkxWldSaThLWlZnMFp6TjVWRXhW
    WjA0NE4ySlFRVmxKVFc5VGIzaFNZMUl4UmtwdlVIbHNTakFyU2pBeVl5dExhVUpoU21aM1J6ZzJV
    VzFQYkRoSGJrUndWRTFxTVFwWmFUZDJNalEzYUhKTWVtOTFhRVZqSzNwV1dETk1TM1ZZU0hWQ04y
    VXljbGhKYVZSM2NVSkRVbmt3V21WWFlrSldPR0YxWmt4YUwyZGhZMmRSVlROSkNuQm1TalZCYjBk
    Q1FVbFNhRUZuY1M5dWFVaE9WRFYyYzI5b1ZuaEphM1J2WWtkMmNrZHZaMDl0UlZwaFpESTNSRTR3
    YTFWT1JqUklhVzFaWjBrNVYxSUthRnAxYkRoMWRtaHpOa3hyVjJKbFJIWnNkakF4U25Wa01ESlFX
    RGhLTjJKdFN6QXZUa1pFYWpGWGJtRm5NbEF6TDJ0Vk5rMUhaV1oyT1drNVlsQlJNZ3BwVUhKTVZW
    bFJaR0ZYUVVsUE0yaFpkMlpOYkhKSVZFWmhTVEZWVVhoSlEyVlNjR3RZTTJ0NlNqbDNiSEF3UWpa
    UVRUYzVDaTB0TFMwdFJVNUVJRkpUUVNCUVVrbFdRVlJGSUV0RldTMHRMUzB0Q2c9PQo=

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG01 }} | base64 --decode

#      - name: Check Kubernetes context
#        run: kubectl config current-context

      - name: Deploy
        run: |
          kubectl get pod -n unilever-dev
