name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main
      - master
env:
  KUBECONFIG_DATA: |
    YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
    cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VSQ1ZF
    TkRRV1V5WjBGM1NVSkJaMGxKWXpSTlVrMDJZWFVyUTJkM1JGRlpTa3R2V2tsb2RtTk9RVkZGVEVK
    UlFYZEdWRVZVVFVKRlIwRXhWVVVLUVhoTlMyRXpWbWxhV0VwMVdsaFNiR042UVdWR2R6QjVUa1JC
    TWsxRVJYaFBWRVY2VFdwR1lVWjNNSHBPUkVFeFRYcEJlRTlVUlRSTmFrWmhUVUpWZUFwRmVrRlNR
    bWRPVmtKQlRWUkRiWFF4V1cxV2VXSnRWakJhV0UxM1oyZEZhVTFCTUVkRFUzRkhVMGxpTTBSUlJV
    SkJVVlZCUVRSSlFrUjNRWGRuWjBWTENrRnZTVUpCVVVObk9VZFpXaTlpTDNSeGRuTldiRGQ2WjFN
    elJubEhTVmhvVFc5WWREQmxTR2R6VFVwUGEzVnZlRkk0YzBOUFF6QnlSbWhZVW5KSFYwOEtXbVZS
    UjJwWFdsZGhTbnBaVERNNFVFaDZUbWQ1WWxjeVMzSlVSMlZGYUhkc1ZtbHlVa3BsZUVSS2MyMHda
    a3hwU1U5V2RFOHpWSG94ZURoTFFsZGlkZ3BqTmxwa01FaHBhMUYyWldKa1JWTjRjbTh2YVRSUGQw
    dENVVnA2YTJka2RtbzBNbkJ6TUROV2NrTkVhMVIwZDFWME1IaDBUMEYyYlZOSlJXOWpiVmhHQ2tG
    aVFWRjVSVzFRYmxFMWJVRlFUbVl3TTJwS01VTk9Wa2xHU2pkNE5VMUhXWFIyVEZWVU9YUTRTVzB3
    UWxCNVZsY3dVbU5hU1d4QlEwcHNTVmhzWVdJS1FWTjBaVzVTWkZCc1JIazFWbkZKT0VSa01rTXlX
    RWwxWkdsUFNVOWxVRTlvWmpCRU5tZEpOVTlTWnpsM1JVb3Jiemd6T1ZneFlVbFZTbVpNYVZOYWRn
    cENMMEZJU1hwSlNtcERSVmxMTUM5a01rdzVia3RDZG5rNVZDdFFRV2ROUWtGQlIycFhWRUpZVFVF
    MFIwRXhWV1JFZDBWQ0wzZFJSVUYzU1VOd1JFRlFDa0puVGxaSVVrMUNRV1k0UlVKVVFVUkJVVWd2
    VFVJd1IwRXhWV1JFWjFGWFFrSlNablp3ZEdGbFRYTndRVGx6Vm10WGVqaFJlRVYxYUdwYVQzRlVR
    VllLUW1kT1ZraFNSVVZFYWtGTloyZHdjbVJYU214amJUVnNaRWRXZWsxQk1FZERVM0ZIVTBsaU0w
    UlJSVUpEZDFWQlFUUkpRa0ZSUVVGWk9USTFaekJTVlFvclZYZGFSVk5VTkRCVlFtWjNPRnBTZHl0
    dlpWSk5Xalk0VVVOWFkyOTROblpPT1daWFkyaDNaa2RyVFdoRk1ITkVZMFZqWlhOU2RUVllZVEZY
    U2pOc0NtODRlalpoUjI1Tk1tdDFOMUppWW5oQ2IxVmxiWEI1Wm1weVJITkZRbTR5VURSa1VtSk5l
    a0ZsYmxSVVpYRkVXaTgxZVU5aVExb3dVbUV3ZWpaWlJVa0tjMU54WjJsWFRHcFRXRWRwVkVsbGJu
    SXhLMEZhVHpsMWQzSlNSM0IzUkc5UGJVSnpOamhsVDFkSWR6UnhOa3h4V0VsMWRFc3liMjEzU2pK
    MU1UTlRlUXBSZW5wek9FVkZVbXg0YkVWWmJraENTVGg1TWpoS1NsTllOVUlyV1RsUFRuTXZiVWt3
    UXpZd1MzWktlRnBPU1RKSFJIWlRjVVJEYUZSc01uaHJlVTA1Q2l0TWJGTm1XQzg0VmxWeWVqVktT
    Mk4xWWxoWFdFeG9ZMk41YzJoeU5GSnRPWHBGUjBkRVdXRm5hM1pQVmpWcVJEVXZRVWhTU0ZKT1Js
    aDJVSGxNWlZRS01HRlJPVVpVVFhoVVRrMVVDaTB0TFMwdFJVNUVJRU5GVWxSSlJrbERRVlJGTFMw
    dExTMEsKICAgIHNlcnZlcjogaHR0cHM6Ly8xMjcuMC4wLjE6NjQ0MwogIG5hbWU6IGNsdXN0ZXIu
    bG9jYWwKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGNsdXN0ZXIubG9jYWwKICAg
    IG5hbWVzcGFjZTogdW5pbGV2ZXItZGV2CiAgICB1c2VyOiBrdWJlcm5ldGVzLWFkbWluCiAgbmFt
    ZToga3ViZXJuZXRlcy1hZG1pbkBjbHVzdGVyLmxvY2FsCmN1cnJlbnQtY29udGV4dDoga3ViZXJu
    ZXRlcy1hZG1pbkBjbHVzdGVyLmxvY2FsCmtpbmQ6IENvbmZpZwpwcmVmZXJlbmNlczoge30KdXNl
    cnM6Ci0gbmFtZToga3ViZXJuZXRlcy1hZG1pbgogIHVzZXI6CiAgICBjbGllbnQtY2VydGlmaWNh
    dGUtZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVUkxWRU5E
    UVdoSFowRjNTVUpCWjBsSldYY3pWa2w2UldoVUwxRjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJR
    WGRHVkVWVVRVSkZSMEV4VlVVS1FYaE5TMkV6Vm1sYVdFcDFXbGhTYkdONlFXVkdkekI1VGtSQk1r
    MUVSWGhQVkVWNlRXcEdZVVozTUhsT1ZFRTBUVlJCZVUxcVFURk9WR1JoVFVSM2VBcElla0ZrUW1k
    T1ZrSkJiMVJHYlhReFdXMVdhRnBITURaWk1uZ3hZek5TYkdOcE1XaGFSekZ3WW01TmVFZFVRVmhD
    WjA1V1FrRk5WRVZIZERGWmJWWjVDbUp0VmpCYVdFMTBXVmRTZEdGWE5IZG5aMFZwVFVFd1IwTlRj
    VWRUU1dJelJGRkZRa0ZSVlVGQk5FbENSSGRCZDJkblJVdEJiMGxDUVZGRVJITkNZazRLWTJoRlYz
    cGFlbEZqUldad1ZqaFFZbVphWm1WeWQwUlhWSFJLVG5CRlRsY3JNVkp1V2pFelJ6Rk5LMmR4VG5a
    SFJXOXZXRGR5VmpKbU5XMXpNakp0V1Fvdk5WRnRURmROV0VKVWVIcEtjakU0VjFwME1GRjBLemwx
    U2tzeGVXdDJkekZoVmxKcVJsSXhjalp3ZEZreVJGbFBTVnBoZUhKdmNsSnlSMUZ1VmpGU0NtVnlR
    azluWmtGelFYbzBlbWxaY0hWaE1uQnZUREZ3VmpKUWVGRlZkU3RhYVdJNVFrRTRkbFZCYnpac1ZW
    aHhVMWR5WW5sVVdHc3ZORXRtYW1kUlNtUUtha2gxZUZwTE5UWnlVVVpwTVVoVWNYSk5Ua0l5T1M5
    eGJEZHZhV0pJVW1GaWJ6RXhNbWhCWm1aUlprVkNabEJ5VkRVMFEyWklLM3BwVkdzM1NHaDNhd3Aw
    Tm5OdU1XTlFSRWxEVVV4WU4xRklZV3RPTjJwSFNtNU9PVXREYW01VWJXMUxZVEZSTlZkaWEwOU1U
    VlpGVFRVMU1HODJha2hwVWpkdldtTjZaRlUyQ2xaS1ZYaEhkM2wyY1VodU5sbDBOek5CWjAxQ1FV
    RkhhbFpxUWxWTlFUUkhRVEZWWkVSM1JVSXZkMUZGUVhkSlJtOUVRVlJDWjA1V1NGTlZSVVJFUVVz
    S1FtZG5ja0puUlVaQ1VXTkVRV3BCVFVKblRsWklVazFDUVdZNFJVRnFRVUZOUWpoSFFURlZaRWwz
    VVZsTlFtRkJSa1lySzIweGNEUjVlV3RFTW5oWFVncGlVSGhFUlZNMlIwNXJObkJOUVRCSFExTnhS
    MU5KWWpORVVVVkNRM2RWUVVFMFNVSkJVVU5TY3psWGJGaHNTVE5tUnpWSWVFMXZSVFJ2ZFdNd1dE
    bGFDbGRPT0ROWmRESlFVbmR3Uldock5tTmlZMWROYWpnMlJHbE5jSEp1VVdoQ2JtcDNRV3MyV2l0
    aUx6VkhUa0ZQY1d0dmFXOXNjMVJuVG10eFNVeGtOVGdLU1U1emNFcHlPVEZZVWxKck4yVnNjMmw0
    T0d4U1QyZFNXRVEySzNad1lXTk5RVE5sYVhvMVRsQmhiVFYzT1cxc1lVWnFTbEkxWTFZemNIbDFW
    MnB5VWdwc1UwOTZia2R5Tm05aWQxSkhTRU52Wm5CaWEzaGxNMGhhTWpSWlFtRmplbFphYjFSU2Qx
    YzBlbTFTTVVkTVJHRjVkV015S3pSRWRYaFdkM2N6VFVaV0NqSjRNbVJ0VDJSUVZHTTJRVEJpV21W
    SmFGZFpSMDh3ZG1sclRsWnpUVk40VjJVeVlXNTFiMWN5VDJOV2RrTTNVMVpzV1dNclpraHZiR3hP
    TWxkdFp6UUtla0puTkdwcVZrVlFOM1YxZVVkS01tNTBSVU5NVkhjMlJFVkNUbVpCZDFkVldGaGlh
    MlpMVlhJNVoxTjRaSEEwUkhRNE1DOXVibWhuUTI4M0NpMHRMUzB0UlU1RUlFTkZVbFJKUmtsRFFW
    UkZMUzB0TFMwSwogICAgY2xpZW50LWtleS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJTVTBFZ1VGSkpW
    a0ZVUlNCTFJWa3RMUzB0TFFwTlNVbEZiM2RKUWtGQlMwTkJVVVZCZHpkQlYzcFlTVkpHY3pKak1F
    aENTRFpXWmtReU16SllNM0U0UVRGck4xTlVZVkpFVm5aMFZWb3laR1I0ZEZSUUNtOUxhbUo0YUV0
    TFJpczJNV1J1SzFweVRuUndiVkFyVlVwcE1XcEdkMVU0WTNsaE9XWkdiV0prUlV4bWRtSnBVM1Jq
    Y0V3NFRsZHNWVmw0VldSaEszRUtZbGRPWnpKRWFVZFhjMkUyU3pCaGVHdEtNV1JWV0hGM1ZHOUlk
    MHhCVFN0Tk5HMUxZbTEwY1dGRE9XRldaR280VlVaTWRtMVpiUzlSVVZCTU1VRkxUd3B3VmtZMmEy
    eHhNamhyTVRWUUswTnVORFJGUTFoWmVEZHpWMU4xWlhFd1FsbDBVakEyY1hwRVVXUjJaalp3WlRa
    SmJYZ3dWMjAyVG1Sa2IxRklNekJJQ25oQldIbzJNQ3RsUVc1NEwzTTBhelZQZURSalNreGxja281
    V0VSM2VVRnJRekVyTUVJeWNFUmxOSGhwV25wbVUyZHZOVEExY0dsdGRGVlBWbTAxUkdrS2VrWlNS
    RTlsWkV0UGIzZzBhMlUyUjFoTk0xWlBiRk5XVFZKelRYSTJhRFVyYlV4bE9YZEpSRUZSUVVKQmIw
    bENRVVZpVTNGVU5FeDRXVWRUVVhWdWVBcGhVMVppYmxWblNVTlliMUJ5YldKb2RXZ3haR3RRTW1a
    RmNXOXNOeTkxZUUwM0x6WjJVMlpRZEN0cU0yWlFaRFZOVURSMGJuVmpMM2RNWldObU5YUnhDbE55
    YlVkVlRtWTNaV3hoTW1sV1IxcDRiMlJEZDNZNVZEUXpVa1JNUzBrelVrdEJOR050YkhVNE4yeFJO
    bFJ2VjJGT1pHeEVUWGRpWTJ0dVNHNHdkbVVLYkVwdFJXTjJVMHB5WTFsMFRsTXlVM3BoWVc5cVdY
    cDBTRXR2UkdWd2NWZHlSakZrTW5ScmIyeEhhemczVFRSdFEyRnJPVE5XWVhoTFJWTkRObUoxWmdv
    dlYzSnNibE13TlRaRWNFWlJXRWN6VHpkbUwxWklaRGRvYmtneGRYSjFOSEEyU1ZGRWJuVmFRbWR0
    WWxwaFpXMTRkM2RqVEVWaU1GSnlNVnBwV0dkWUNuazNjVkJKVTNSd1prSnZUVFF6VERsRWFVUmtk
    VmQwV25SbksxSmhiWHB4UVRKWUwzRlNkelZ6VkZoNVFuSkVVa2REUVd4MFVYcFFiRzFPVlc1WlFV
    Y0tPSGhuWjNaaVJVTm5XVVZCTWtSTE5GaGFaMG9yV2pSdU4wTlNSMEZhUlVsWFdISk5jSEZ6WVM5
    bU4wRjJWMmhqTWtsVU5FRlRhV2hoU21kblVtMTBUZ3BOY1ZOMmNIbHFaV3gwVVZReGFFaERiRVky
    VW5oaGRFSkNMMWRTTTBaVVltNXhXbFpoYzFwMVRtdFNhVzFRVWpKSFNEaHphVkk0YTFkTlRVSTNi
    ekJaQ25WVlRVUlpUazFDUmxGTlVURXZka1pRTjJwcFFXNW1NRkJKZVRsdlRtbDRWVzlOUW1wNUwy
    bHVObUV3UW1FMVEwUlZVekJ6WXpoRFoxbEZRVFUzWVRjS2FXMUxjRWc1YkUxTE9XcFNhbXR6Y0dj
    NUwzSk5VSFZzY1dwMlJHdHplV2swTUZrNVowcHdOVFYyTXpsSk1VMVpNMkZhUkhrM2NGQmhWRzl0
    UWtzeFpBcExZV3hPV0U4NFVHZGxiMngzYmxGSllUTkJPR2RxZGxoSk9YWkJXSGx6VmtKNFExSk5k
    eXRsUlZvck9VVlJWMFI1T1N0NFNXRXJUWHBrVkRGSFp6RmpDbXR6VWl0dWRDOUdNRXQwTlZsSFdF
    SXpSVUk0UmtWbFFsZFJNbXhVYUZSaE5YUnhTR3RzYTBObldVSXJORXd3T0VORFkwdG1RblZZZUU4
    emEzRXpXRWdLT1ZnME1qZGpSMjluUTBscGVHbFdLekpCU1c1M0t6RTVNRnBHV0Zsck9YRjNhVlp1
    Y0RFclEwTnlTV1JrYTNwSUx5OTJlV3R1T1ZkeFdFcFNZVTlrS3dwWmMxWk5TbGR0TW5CVmJISXhS
    VTlsVDNKM2NrOU5RaXMyZFhGMVZXUllTbTAxT1ZjMmJETXZUVGcxYkhkd1lrOTJOMU0zYlVOUldX
    bE5kMk52YVRkdENtRnZWekoyTTFwNlJsVlZaVGxHV2taTVUxbFRSbmRMUW1kR2FFeG9SMnN5VFZS
    WlIzRnZWRzE1VDNWTk4zQlFiVFZ2YzNsNVUzb3lUM2M0WTFaV1JpOEtaVmcwWnpONVZFeFZaMDQ0
    TjJKUVFWbEpUVzlUYjNoU1kxSXhSa3B2VUhsc1NqQXJTakF5WXl0TGFVSmhTbVozUnpnMlVXMVBi
    RGhIYmtSd1ZFMXFNUXBaYVRkMk1qUTNhSEpNZW05MWFFVmpLM3BXV0ROTVMzVllTSFZDTjJVeWNs
    aEphVlIzY1VKRFVua3dXbVZYWWtKV09HRjFaa3hhTDJkaFkyZFJWVE5KQ25CbVNqVkJiMGRDUVVs
    U2FFRm5jUzl1YVVoT1ZEVjJjMjlvVm5oSmEzUnZZa2QyY2tkdlowOXRSVnBoWkRJM1JFNHdhMVZP
    UmpSSWFXMVpaMGs1VjFJS2FGcDFiRGgxZG1oek5reHJWMkpsUkhac2RqQXhTblZrTURKUVdEaEtO
    Mkp0U3pBdlRrWkVhakZYYm1Gbk1sQXpMMnRWTmsxSFpXWjJPV2s1WWxCUk1ncHBVSEpNVlZsUlpH
    RlhRVWxQTTJoWmQyWk5iSEpJVkVaaFNURlZVWGhKUTJWU2NHdFlNMnQ2U2psM2JIQXdRalpRVFRj
    NUNpMHRMUzB0UlU1RUlGSlRRU0JRVWtsV1FWUkZJRXRGV1MwdExTMHRDZz09Cg==
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        mkdir -p $HOME/.kube
    - name: Install kubectl
      run: |
        sudo apt-get update && sudo apt-get install -y kubectl
    - name: Apply Kubernetes manifests
      run: |
        kubectl get po
